-- ==========================================
-- SCRIPT DE CRIAÇÃO DO SCHEMA SUPABASE (POSTGRESQL)
-- Baseado no models.py do Portal de Indicadores
-- ==========================================

-- 1. Produtividade
CREATE TABLE public.produtividade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipe TEXT,
    tipo_equipe TEXT,
    setor TEXT,
    data DATE,
    csd TEXT,
    ocupacao DOUBLE PRECISION,
    produtividade_pct DOUBLE PRECISION,
    eficiencia_pct DOUBLE PRECISION,
    eficacia_pct DOUBLE PRECISION,
    notas_executadas DOUBLE PRECISION,
    notas_interrompidas DOUBLE PRECISION DEFAULT 0.0,
    notas_rejeitadas DOUBLE PRECISION DEFAULT 0.0,
    ociosidade_min DOUBLE PRECISION,
    desvios_min DOUBLE PRECISION,
    deslocamento_min DOUBLE PRECISION,
    hhp_min DOUBLE PRECISION,
    hhr_min DOUBLE PRECISION DEFAULT 0.0,
    saida_base_min DOUBLE PRECISION DEFAULT 0.0,
    retorno_base_min DOUBLE PRECISION DEFAULT 0.0,
    hora_extra_min DOUBLE PRECISION DEFAULT 0.0
);

-- Índices Recomendados para Produtividade
CREATE INDEX idx_produtividade_equipe ON public.produtividade(equipe);
CREATE INDEX idx_produtividade_setor ON public.produtividade(setor);
CREATE INDEX idx_produtividade_data ON public.produtividade(data);

-- 2. Auditorias 5S
CREATE TABLE public.auditorias_5s (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_auditoria DATE,
    base TEXT,
    inspetor TEXT,
    local_auditado TEXT,
    tipo_auditoria TEXT,
    conformidade_pct DOUBLE PRECISION,
    nota_1s DOUBLE PRECISION,
    nota_2s DOUBLE PRECISION,
    nota_3s DOUBLE PRECISION,
    nota_4s DOUBLE PRECISION,
    nota_5s DOUBLE PRECISION
);

CREATE INDEX idx_auditorias_5s_data ON public.auditorias_5s(data_auditoria);
CREATE INDEX idx_auditorias_5s_base ON public.auditorias_5s(base);


-- 3. Frota Custos
CREATE TABLE public.frota_custos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa TEXT,
    veiculo_id TEXT,
    data_solicitacao DATE,
    modelo TEXT,
    marca TEXT,
    tipo TEXT,
    ano_veiculo INTEGER,
    setor TEXT,
    regional TEXT,
    fornecedor TEXT,
    nome_servico TEXT,
    tipo_manutencao TEXT,
    custo_val DOUBLE PRECISION DEFAULT 0.0
);

CREATE INDEX idx_frota_placa ON public.frota_custos(placa);
CREATE INDEX idx_frota_data ON public.frota_custos(data_solicitacao);


-- 4. Indisponibilidade
CREATE TABLE public.indisponibilidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mes_ref TEXT,
    regional TEXT,
    tipo_desvio TEXT,
    checado BOOLEAN DEFAULT FALSE,
    valor DOUBLE PRECISION DEFAULT 0.0,
    tempo DOUBLE PRECISION DEFAULT 0.0
);

CREATE INDEX idx_indisp_mes ON public.indisponibilidade(mes_ref);
CREATE INDEX idx_indisp_regional ON public.indisponibilidade(regional);

-- 5. Logs de Sincronização
CREATE TABLE public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT,
    last_sync TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT,
    records_processed INTEGER
);

CREATE INDEX idx_synclog_file ON public.sync_logs(source_file);


-- 6. Rejeições
CREATE TABLE public.rejeicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regional TEXT,
    setor TEXT,
    nota TEXT,
    tipo TEXT,
    equipe TEXT,
    descricao TEXT,
    cidade TEXT,
    codigo_motivo TEXT,
    motivo TEXT,
    backoffice_em TEXT,
    telefone_contato TEXT,
    data_conclusao DATE,
    num_rejeicoes INTEGER DEFAULT 1,
    eletricista TEXT,
    analista TEXT,
    status TEXT
);

CREATE INDEX idx_rejeicoes_data ON public.rejeicoes(data_conclusao);
CREATE INDEX idx_rejeicoes_regional ON public.rejeicoes(regional);


-- 7. Logística - MB52
CREATE TABLE public.logccm_mb52 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regional TEXT,
    material TEXT,
    grupo TEXT,
    grupo_nome TEXT,
    valor_virtual DOUBLE PRECISION DEFAULT 0.0,
    valor_fisico DOUBLE PRECISION DEFAULT 0.0,
    valor_fisico_sem_pedalada DOUBLE PRECISION DEFAULT 0.0
);


-- 8. Logística - Itens
CREATE TABLE public.logccm_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regional TEXT,
    tipo TEXT,
    material TEXT,
    descricao TEXT,
    grupo TEXT,
    grupo_nome TEXT,
    deposito TEXT,
    saldo DOUBLE PRECISION DEFAULT 0.0,
    valor DOUBLE PRECISION DEFAULT 0.0
);


-- 9. Logística - Ruptura
CREATE TABLE public.logccm_ruptura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regional TEXT,
    material TEXT,
    descricao TEXT,
    grupo TEXT,
    grupo_nome TEXT,
    data_deslig DATE,
    qtd_necessaria DOUBLE PRECISION DEFAULT 0.0,
    qtd_analisar DOUBLE PRECISION DEFAULT 0.0,
    saldo_fisico DOUBLE PRECISION DEFAULT 0.0,
    saldo_sistema DOUBLE PRECISION DEFAULT 0.0,
    diagrama TEXT,
    inventario TEXT
);


-- 10. Logística - Serial
CREATE TABLE public.logccm_serial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regional TEXT,
    serial TEXT,
    material TEXT,
    descricao TEXT,
    status TEXT,
    deposito TEXT
);


-- 11. APR Records
CREATE TABLE public.apr_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector TEXT,
    data DATE,
    equipe TEXT,
    setor_name TEXT,
    notas_exec DOUBLE PRECISION DEFAULT 0.0,
    apr_digital DOUBLE PRECISION DEFAULT 0.0,
    efetividade DOUBLE PRECISION DEFAULT 0.0
);


-- 12. Saída Base Records
CREATE TABLE public.saida_base_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE,
    regional TEXT,
    equipe TEXT,
    motivo TEXT,
    tempo_embarque DOUBLE PRECISION DEFAULT 0.0,
    custo_total DOUBLE PRECISION DEFAULT 0.0,
    ofensor TEXT
);


-- 13. System Configs
CREATE TABLE public.system_configs (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- POLÍTICAS DE SEGURANÇA (RLS - Row Level Security)
-- Habilitando RLS para todas as tabelas, mas permitindo leitura pública inicial
-- ==========================================

DO $$
DECLARE
    t_name text;
BEGIN
    FOR t_name IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename IN ('produtividade', 'auditorias_5s', 'frota_custos', 'indisponibilidade', 'sync_logs', 'rejeicoes', 'logccm_mb52', 'logccm_item', 'logccm_ruptura', 'logccm_serial', 'apr_records', 'saida_base_records', 'system_configs')) LOOP
        EXECUTE 'ALTER TABLE public.' || quote_ident(t_name) || ' ENABLE ROW LEVEL SECURITY;';
        -- Criando política genérica de SELECT (Apenas usuários logados)
        EXECUTE 'CREATE POLICY ' || quote_ident('permitir_leitura_auth_' || t_name) || ' ON public.' || quote_ident(t_name) || ' FOR SELECT TO authenticated USING (true);';
        -- Service Role (Robô local usando url/key) tem ALL access bypassando RLS (Padrão no Supabase com Service Key)
    END LOOP;
END
$$;

