-- ============================================================
-- Indicator Tables for ERP Eletromarquez
-- Supabase Migration: indicator_tables_supabase.sql
-- Execute no SQL Editor do Supabase
-- ============================================================

-- produtividade
CREATE TABLE IF NOT EXISTS produtividade (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipe                TEXT,
  tipo_equipe           TEXT,
  setor                 TEXT,
  data                  DATE,
  csd                   TEXT,
  ocupacao              FLOAT,
  produtividade_pct     FLOAT,
  eficiencia_pct        FLOAT,
  eficacia_pct          FLOAT,
  notas_executadas      FLOAT,
  notas_interrompidas   FLOAT DEFAULT 0,
  notas_rejeitadas      FLOAT DEFAULT 0,
  ociosidade_min        FLOAT,
  desvios_min           FLOAT,
  deslocamento_min      FLOAT,
  hhp_min               FLOAT,
  saida_base_min        FLOAT DEFAULT 0,
  retorno_base_min      FLOAT DEFAULT 0,
  hora_extra_min        FLOAT DEFAULT 0
);
ALTER TABLE produtividade ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON produtividade FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- auditorias_5s
CREATE TABLE IF NOT EXISTS auditorias_5s (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_auditoria    DATE,
  base              TEXT,
  inspetor          TEXT,
  local_auditado    TEXT,
  tipo_auditoria    TEXT,
  conformidade_pct  FLOAT,
  nota_1s           FLOAT,
  nota_2s           FLOAT,
  nota_3s           FLOAT,
  nota_4s           FLOAT,
  nota_5s           FLOAT
);
ALTER TABLE auditorias_5s ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON auditorias_5s FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- frota_custos
CREATE TABLE IF NOT EXISTS frota_custos (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placa             TEXT,
  veiculo_id        TEXT,
  data_solicitacao  DATE,
  modelo            TEXT,
  marca             TEXT,
  tipo              TEXT,
  ano_veiculo       INT,
  setor             TEXT,
  regional          TEXT,
  fornecedor        TEXT,
  nome_servico      TEXT,
  tipo_manutencao   TEXT,
  custo_val         FLOAT DEFAULT 0
);
ALTER TABLE frota_custos ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON frota_custos FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- indisponibilidade
CREATE TABLE IF NOT EXISTS indisponibilidade (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes_ref       TEXT,
  regional      TEXT,
  tipo_desvio   TEXT,
  checado       BOOLEAN DEFAULT FALSE,
  valor         FLOAT DEFAULT 0,
  tempo         FLOAT DEFAULT 0
);
ALTER TABLE indisponibilidade ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON indisponibilidade FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- rejeicoes
CREATE TABLE IF NOT EXISTS rejeicoes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional          TEXT,
  setor             TEXT,
  nota              TEXT,
  tipo              TEXT,
  equipe            TEXT,
  descricao         TEXT,
  cidade            TEXT,
  codigo_motivo     TEXT,
  motivo            TEXT,
  backoffice_em     TEXT,
  telefone_contato  TEXT,
  data_conclusao    DATE,
  num_rejeicoes     INT DEFAULT 1,
  eletricista       TEXT,
  analista          TEXT,
  status            TEXT
);
ALTER TABLE rejeicoes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON rejeicoes FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- logccm_mb52
CREATE TABLE IF NOT EXISTS logccm_mb52 (
  id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional                     TEXT,
  material                     TEXT,
  grupo                        TEXT,
  grupo_nome                   TEXT,
  valor_virtual                FLOAT DEFAULT 0,
  valor_fisico                 FLOAT DEFAULT 0,
  valor_fisico_sem_pedalada    FLOAT DEFAULT 0
);
ALTER TABLE logccm_mb52 ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON logccm_mb52 FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- logccm_item
CREATE TABLE IF NOT EXISTS logccm_item (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional    TEXT,
  tipo        TEXT,
  material    TEXT,
  descricao   TEXT,
  grupo       TEXT,
  grupo_nome  TEXT,
  deposito    TEXT,
  saldo       FLOAT DEFAULT 0,
  valor       FLOAT DEFAULT 0
);
ALTER TABLE logccm_item ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON logccm_item FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- logccm_ruptura
CREATE TABLE IF NOT EXISTS logccm_ruptura (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional        TEXT,
  material        TEXT,
  descricao       TEXT,
  grupo           TEXT,
  grupo_nome      TEXT,
  data_deslig     DATE,
  qtd_necessaria  FLOAT DEFAULT 0,
  qtd_analisar    FLOAT DEFAULT 0,
  saldo_fisico    FLOAT DEFAULT 0,
  saldo_sistema   FLOAT DEFAULT 0,
  diagrama        TEXT,
  inventario      TEXT
);
ALTER TABLE logccm_ruptura ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON logccm_ruptura FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- logccm_serial
CREATE TABLE IF NOT EXISTS logccm_serial (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional    TEXT,
  serial      TEXT,
  material    TEXT,
  descricao   TEXT,
  status      TEXT,
  deposito    TEXT
);
ALTER TABLE logccm_serial ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON logccm_serial FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- apr_records
CREATE TABLE IF NOT EXISTS apr_records (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sector      TEXT,
  data        DATE,
  equipe      TEXT,
  setor_name  TEXT,
  notas_exec  FLOAT DEFAULT 0,
  apr_digital FLOAT DEFAULT 0,
  efetividade FLOAT DEFAULT 0
);
ALTER TABLE apr_records ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON apr_records FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- saida_base_records
CREATE TABLE IF NOT EXISTS saida_base_records (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data             DATE,
  regional         TEXT,
  equipe           TEXT,
  motivo           TEXT,
  tempo_embarque   FLOAT DEFAULT 0,
  custo_total      FLOAT DEFAULT 0,
  ofensor          TEXT
);
ALTER TABLE saida_base_records ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON saida_base_records FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- sync_logs
CREATE TABLE IF NOT EXISTS sync_logs (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_file         TEXT,
  last_sync           TIMESTAMPTZ DEFAULT NOW(),
  status              TEXT,
  records_processed   INT
);
ALTER TABLE sync_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON sync_logs FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- system_configs
CREATE TABLE IF NOT EXISTS system_configs (
  key         TEXT PRIMARY KEY,
  value       TEXT,
  description TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE system_configs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "allow_all_read" ON system_configs FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Configuração padrão: meta de produtividade
INSERT INTO system_configs (key, value, description)
VALUES ('meta_produtividade', '85', 'Meta global de produtividade (%)')
ON CONFLICT (key) DO NOTHING;
