-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Unidades de Medida
CREATE TABLE IF NOT EXISTS unidade_medida (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome TEXT NOT NULL
);

-- 2. Tipos de Material
CREATE TABLE IF NOT EXISTS tipo_material (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome TEXT NOT NULL,
  justificar BOOLEAN DEFAULT FALSE
);

-- 3. Tipos de Justificativa
CREATE TABLE IF NOT EXISTS tipo_justificativa (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome TEXT NOT NULL,
  destino TEXT, -- 'colaborador', etc.
  estoque_colaborador TEXT -- 'entrada', etc.
);

-- 4. Materiais
CREATE TABLE IF NOT EXISTS materiais (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  codigo TEXT UNIQUE NOT NULL,
  descricao TEXT NOT NULL,
  tipo_material_id BIGINT REFERENCES tipo_material(id),
  unidade_id BIGINT REFERENCES unidade_medida(id),
  seriado BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Estoques (Locais de Armazenamento)
CREATE TABLE IF NOT EXISTS estoques (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome TEXT NOT NULL,
  tipo_estoque TEXT, -- 'Equipe', 'Depósito', 'Individual'
  deposito_vinculado TEXT -- Optional, based on 'Depósito' column
);

-- 6. Itens em Estoque (Saldo)
CREATE TABLE IF NOT EXISTS itens_estoque (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  estoque_id BIGINT REFERENCES estoques(id) ON DELETE CASCADE,
  material_id BIGINT REFERENCES materiais(id) ON DELETE RESTRICT,
  saldo NUMERIC DEFAULT 0,
  UNIQUE(estoque_id, material_id)
);

-- 7. Perfis de Usuários (Profiles) - Linking to Supabase Auth
-- We include legacy_id to map from the old Excel sheet if needed.
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  legacy_id BIGINT UNIQUE, -- ID from the Excel 'usuario' sheet
  matricula TEXT,
  full_name TEXT,
  email TEXT,
  role TEXT DEFAULT 'user', -- 'admin', 'manager', 'user'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Fallback for existing users without Auth account (for data migration purposes)
CREATE TABLE IF NOT EXISTS usuarios_legacy (
  id BIGINT PRIMARY KEY,
  matricula TEXT,
  nome TEXT,
  email TEXT
);

-- 8. Movimentações
CREATE TABLE IF NOT EXISTS movimentacoes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo TEXT NOT NULL, -- 'Transferência', 'Saída', 'Entrada'
  estoque_origem_id BIGINT REFERENCES estoques(id),
  estoque_destino_id BIGINT REFERENCES estoques(id),
  criado_por_id BIGINT, -- Can reference profiles.legacy_id or a raw ID
  finalizado_por_id BIGINT,
  criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  finalizado_em TIMESTAMP WITH TIME ZONE,
  situacao TEXT DEFAULT 'Pendente', -- 'Aprovada', 'Pendente'
  referencia TEXT
);

-- 9. Itens das Movimentações
CREATE TABLE IF NOT EXISTS itens_movimentacoes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movimentacao_id BIGINT REFERENCES movimentacoes(id) ON DELETE CASCADE,
  material_id BIGINT REFERENCES materiais(id),
  quantidade NUMERIC NOT NULL,
  valor NUMERIC,
  justificativa_id BIGINT REFERENCES tipo_justificativa(id),
  observacao TEXT
);

-- Policies (RLS) - Basic Setup
ALTER TABLE materiais ENABLE ROW LEVEL SECURITY;
ALTER TABLE estoques ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone for now (Authenticated users)
CREATE POLICY "Public read access" ON materiais FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Public read access" ON estoques FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Public read access" ON movimentacoes FOR SELECT USING (auth.role() = 'authenticated');
